In [1]:
from pybrain.tools.shortcuts import buildNetwork

In [101]:
net = buildNetwork(1, 4, 4, 1)

In [102]:
net.activate([1])

array([ 0.89824076])

In [103]:
from pybrain.datasets import SupervisedDataSet

In [104]:
ds = SupervisedDataSet(1, 1)

In [105]:
import numpy as np

In [106]:
s = np.random.uniform(size=50)

In [107]:
trainingoutput = np.array(10*s)

In [108]:
traininginput = trainingoutput*trainingoutput

In [109]:
trainingdata = np.array([traininginput,trainingoutput])

In [110]:
trainingdata = trainingdata.T

In [111]:
from pybrain.supervised.trainers import BackpropTrainer

In [112]:
for i in range(50):
    ds.addSample((trainingdata[i,0]), (trainingdata[i,1]))

In [113]:
len(ds)

50

In [114]:
trainer = BackpropTrainer(net, ds)

In [115]:
trainer.train()

4.7721381883033693

In [116]:
trainer.trainUntilConvergence()

([2.4552771462523442,
  2.466710454634478,
  2.4219683470205777,
  2.3690766662557166,
  2.3160554323185645,
  2.2152646121842658,
  2.0987480494433748,
  1.9258486788069087,
  1.8554673104972459,
  1.7673675271813751,
  1.6890028549550746,
  1.6149803963657681,
  1.5308035460967395,
  1.4072448850174497,
  1.3293424537121821,
  1.2224601827642452,
  1.1362153431912763,
  1.067998063347908,
  0.95400799811089776,
  0.85952909309016789,
  0.77446018962995589,
  0.70291235874788516,
  0.7030085304842546,
  0.58827696611539093,
  0.68903843719789759,
  0.813860709239693,
  0.48325509936272315,
  0.43979058380155273,
  0.40374419072885198,
  0.72404219755411814,
  0.36999772452290136,
  1.1949982401483172,
  1.8098112996476949,
  1.4408979064948169,
  1.1712618098966299,
  1.1623430065900775,
  0.75251129221848956,
  0.64642571841265939,
  0.63565113278505869,
  0.83180009085403728,
  0.60979269534959823,
  0.74475614979778337,
  0.70369664397201082,
  0.74225625842350706,
  1.127477628729

In [117]:
print net

FeedForwardNetwork-32
   Modules:
    [<BiasUnit 'bias'>, <LinearLayer 'in'>, <SigmoidLayer 'hidden0'>, <SigmoidLayer 'hidden1'>, <LinearLayer 'out'>]
   Connections:
    [<FullConnection 'FullConnection-26': 'in' -> 'hidden0'>, <FullConnection 'FullConnection-27': 'hidden0' -> 'hidden1'>, <FullConnection 'FullConnection-28': 'hidden1' -> 'out'>, <FullConnection 'FullConnection-29': 'bias' -> 'out'>, <FullConnection 'FullConnection-30': 'bias' -> 'hidden0'>, <FullConnection 'FullConnection-31': 'bias' -> 'hidden1'>]



In [126]:
net.activate([1])

array([ 1.27486969])

In [127]:
net.activate([4])

array([ 2.29150977])

In [128]:
net.activate([9])

array([ 3.60072216])

In [129]:
net.activate([16])

array([ 4.29900189])

In [130]:
net.activate([25])

array([ 4.88355796])